### PR TITLE
EvCoercion was removed, fixes #2.

### LINKED ISSUE #2: EvCoercion not in scope with ghc 8.6.1
Can the thoralf plugin be made to compile with `ghc-8.6.1`?

```
- resolver: lts-12.6
+ resolver: nightly-2018-10-02
```

```
the-thoralf-plugin> stack install
...
[17 of 18] Compiling ThoralfPlugin.ThoralfPlugin ( src/ThoralfPlugin/ThoralfPlugin.hs
, .stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/ThoralfPlugin/ThoralfPlugin.o )

/Users/pdejoux/dev/src/haskell/the-thoralf-plugin/src/ThoralfPlugin/ThoralfPlugin.hs:269:3: error:
    Data constructor not in scope:
      EvCoercion :: TyCoRep.Coercion -> EvTerm
    |
269 |   EvCoercion $ mkUnivCo (PluginProv s) Nominal t1 t2
    |   ^^^^^^^^^^

Completed 3 action(s).

--  While building custom Setup.hs for package thoralf-plugin-0.1.0.0 using:
...
    Process exited with code: ExitFailure 1
```

### PR DESCRIPTION
**Pull request by philderbeast**

### CODE REVIEW

**Comment by goldfirere** [comment]
Does this actually work in practice? I'd be surprised if this is all it takes to ensure compatibility with GHC 8.6...

Many thanks for the contribution.
